In [1]:
import numpy as np

In [2]:
new_list = [1,2,3]

In [3]:
np.array(new_list)

array([1, 2, 3])

In [4]:
new_list = [[1,2,3],[4,5,6],[7,8,9]]

In [5]:
np.array(new_list)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [8]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [9]:
np.zeros(3)

array([0., 0., 0.])

In [10]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [11]:
np.ones(3)

array([1., 1., 1.])

In [12]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [13]:
np.linspace(0,10,100)

array([ 0.        ,  0.1010101 ,  0.2020202 ,  0.3030303 ,  0.4040404 ,
        0.50505051,  0.60606061,  0.70707071,  0.80808081,  0.90909091,
        1.01010101,  1.11111111,  1.21212121,  1.31313131,  1.41414141,
        1.51515152,  1.61616162,  1.71717172,  1.81818182,  1.91919192,
        2.02020202,  2.12121212,  2.22222222,  2.32323232,  2.42424242,
        2.52525253,  2.62626263,  2.72727273,  2.82828283,  2.92929293,
        3.03030303,  3.13131313,  3.23232323,  3.33333333,  3.43434343,
        3.53535354,  3.63636364,  3.73737374,  3.83838384,  3.93939394,
        4.04040404,  4.14141414,  4.24242424,  4.34343434,  4.44444444,
        4.54545455,  4.64646465,  4.74747475,  4.84848485,  4.94949495,
        5.05050505,  5.15151515,  5.25252525,  5.35353535,  5.45454545,
        5.55555556,  5.65656566,  5.75757576,  5.85858586,  5.95959596,
        6.06060606,  6.16161616,  6.26262626,  6.36363636,  6.46464646,
        6.56565657,  6.66666667,  6.76767677,  6.86868687,  6.96

In [14]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [15]:
np.random.rand(5)

array([0.6115389 , 0.21870883, 0.87287181, 0.85145166, 0.26852471])

In [16]:
np.random.randn(5)

array([ 0.89853624, -1.56666406, -1.01167398, -1.83225206, -0.22862466])

In [17]:
np.random.rand(5,2)

array([[0.23723344, 0.83302119],
       [0.65296049, 0.1035862 ],
       [0.51960017, 0.36799108],
       [0.51449282, 0.67441688],
       [0.69396227, 0.34185245]])

In [18]:
np.random.randn(2,5)

array([[ 0.9773369 ,  0.06574278,  1.76944501,  0.52384762,  1.03897445],
       [ 0.74180702, -1.310341  , -0.46173276, -0.5207946 ,  0.07496825]])

In [20]:
np.random.randint(1,50,10)

array([40,  2, 29,  1, 13, 21, 47, 46, 28, 34])

In [21]:
n = np.arange(0,20)

In [23]:
n.reshape(5,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [24]:
random = np.random.randint(0,20,10)

In [25]:
random

array([17, 19, 19,  4, 14,  9,  2, 14, 18, 17])

In [27]:
random.max()

19

In [28]:
random.min()

2

In [29]:
random.argmax()

1

In [30]:
random.argmin()

6

In [32]:
random.shape

(10,)

In [33]:
random.reshape(5,2)

array([[17, 19],
       [19,  4],
       [14,  9],
       [ 2, 14],
       [18, 17]])