# Numpy Indexing and Selection

In [1]:
import numpy as np

In [2]:
arr = np.arange(0,11)

In [3]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [4]:
arr[8]

8

In [5]:
arr[1:5]

array([1, 2, 3, 4])

In [6]:
arr[::2]

array([ 0,  2,  4,  6,  8, 10])

In [7]:
arr[5:]

array([ 5,  6,  7,  8,  9, 10])

In [8]:
arr[5:] = 100

In [9]:
arr

array([  0,   1,   2,   3,   4, 100, 100, 100, 100, 100, 100])

In [10]:
arr = np.arange(0,11)

In [11]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [12]:
slice_of_arr = arr[0:6]

In [13]:
slice_of_arr

array([0, 1, 2, 3, 4, 5])

In [3]:
arr_2d = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [4]:
arr_2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [5]:
arr_2d[0][0]

1

In [6]:
arr_2d[1][2]

6

In [7]:
arr_2d[1,2]

6

In [9]:
arr_2d[:2,:3]

array([[1, 2, 3],
       [4, 5, 6]])

In [12]:
arr = np.array([1,2,3,4,5,6,7,8,9])

In [13]:
arr > 5

array([False, False, False, False, False,  True,  True,  True,  True])

In [14]:
arr[arr < 5]

array([1, 2, 3, 4])

In [15]:
arr = np.arange(50).reshape(10,5)

In [16]:
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49]])